function [pose, cov] = matchScanCustom(curr_points, ref_points, pose_guess)
    [pose, stats] = matchScansGrid(...
        lidarScan(curr_points),... 
        lidarScan(ref_points), ...
        'InitialPose', pose_guess ...
    );
    cov = stats.Covariance;
end