function pose = matchScanCustom(curr_points, ref_points, pose_guess)
    pose = matchScansGrid(...
        lidarScan(curr_points),... 
        lidarScan(ref_points), ...
        'InitialPose', pose_guess ...
    );
end